databaseChangeLog:
  - changeSet:
      id: 5
      author: you
      changes:
        - createTable:
            tableName: Products
            columns:
              - column:
                  name: id
                  type: int
                  autoIncrement: true
                  constraints:
                    primaryKey: true
              - column:
                  name: name
                  type: varchar(255)
                  constraints:
                    nullable: false
              - column:
                  name: price
                  type: decimal
                  constraints:
                    nullable: false
              - column:
                  name: description
                  type: text
              - column:
                  name: category_id
                  type: int
                  constraints:
                    nullable: false
                    foreignKeyName: fk_products_category_id
                    referencedTableName: ProductCategories
                    referencedColumnNames: id
              - column:
                  name: manufacturer_id
                  type: int
                  constraints:
                    nullable: false
                    foreignKeyName: fk_products_manufacturer_id
                    referencedTableName: Manufacturers
                    referencedColumnNames: id
